//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektHotele.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelsDBB
    {
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public string Numer { get; set; }
        public string Standard { get; set; }
        public Nullable<System.DateTime> DataDodanie { get; set; }
        public string opis { get; set; }
        public string Cena { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public Nullable<System.DateTime> WynajemOd { get; set; }
        public Nullable<System.DateTime> WynajemDo { get; set; }
        public Nullable<int> RodzajPlatnosci { get; set; }
        public Nullable<int> Stan { get; set; }
    
        public virtual Rodzpl Rodzpl { get; set; }
        public virtual Stann Stann { get; set; }
    }
}
