//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektHotele.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public string Numer { get; set; }
        public string Standard { get; set; }
        public System.DateTime DataDodania { get; set; }
        public string Opis { get; set; }
        public string Stan { get; set; }
        public string Cena { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public Nullable<System.DateTime> wynajemod { get; set; }
        public Nullable<System.DateTime> wynajemdo { get; set; }
        public string rodzjplatnosci { get; set; }
    }
}
