//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektHotele.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelsDBEntities1 : DbContext
    {
        public HotelsDBEntities1()
            : base("name=HotelsDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HotelsDBB> HotelsDBBs { get; set; }
        public virtual DbSet<Rodzpl> Rodzpls { get; set; }
        public virtual DbSet<Stann> Stanns { get; set; }
    }
}
